import {Header} from "../../components/Header";
import CheckoutModal  from "../../components/SellOutCheckOut/CheckoutModal";
import { useSelloutModal } from "../../context/SellOutProvider";
import { generateMockData } from "../../utils/generateMockData";
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import { useState } from 'react';
import { MarketCard } from '..';

export default function MarketPlace() {
	const { sellOutModalOpen, openSellOutModal, closeModal } = useSelloutModal();
	const [checkOutData, setCheckOutData] = useState<any>(null);
	return (
		<div className={''}>
			<Head>
				<title>Create-Web3 App</title>
				<meta name="description" content="Generated by npx create-web3" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			<main
				style={{
					minHeight: '60vh',
					flex: '1',
					display: 'flex',
					flexDirection: 'column',
					justifyContent: 'center',
					alignItems: 'center',
				}}
			>
				{/* <button onClick={openSellOutModal}>Open Sellout modal</button> */}
				{sellOutModalOpen && checkOutData && (
					<CheckoutModal promoCode address data={checkOutData} open={sellOutModalOpen} onClose={closeModal} />
				)}
				<div className="grid md:grid-cols-3 grid-cols-1 mt-10 w-[80%] ">
					{generateMockData().map((data, i) => (
						<div key={i}>
							<MarketCard data={data} setCheckOutData={setCheckOutData} />
						</div>
					))}
				</div>
			</main>
		</div>
	);
}
